name: kazakh_invest
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: 3.0.9
  #for svg pictures
  flutter_svg: 0.19.0
  #for store local values
  shared_preferences: 0.5.12
  #provider package for state management
  provider: 4.3.2
  #to download and cache images
  cached_network_image: 2.3.0
  #file permission
  permission_handler: 5.0.1
  #for video playing
  chewie: 0.9.10
  #animated dots
  smooth_page_indicator: 0.2.0
  #url launcher
  url_launcher: 5.7.8

  #html content
  flutter_html: 0.11.1

  #web view
  webview_flutter: 1.0.6
  flutter_staggered_grid_view: 0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/png/
    - lib/assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: lib/assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: lib/assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: lib/assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: lib/assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/montserrat/Montserrat-Light.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
